name: billing_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  image_picker: ^1.1.2
  path: ^1.9.1
  firebase_core: ^3.12.1
  cloud_firestore: ^5.6.5
  provider: ^6.1.2
  shared_preferences: ^2.2.0
  flutter_bluetooth_serial: ^0.4.0
  esc_pos_bluetooth: ^0.4.1
  esc_pos_utils: ^1.1.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/NotoSansTelugu-Regular.ttf  # Added Telugu font
    - assets/fonts/NotoSans-Bold.ttf

  fonts:
    - family: NotoSansTelugu
      fonts:
        - asset: assets/fonts/NotoSansTelugu-Regular.ttf
        - asset: assets/fonts/NotoSans-Bold.ttf
          weight: 700