// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpF1sOeS5lXXKhvnLIichapafkzfbAjX0',
    appId: '1:10860558957:web:caa92c7939e2de9a58dd64',
    messagingSenderId: '10860558957',
    projectId: 'billingapp-53d4c',
    authDomain: 'billingapp-53d4c.firebaseapp.com',
    storageBucket: 'billingapp-53d4c.firebasestorage.app',
    measurementId: 'G-0884D9ZGV5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIAChVLfw5qhyZxomxgPa5iKFk5hClbPY',
    appId: '1:10860558957:android:2f9517ef53336d6558dd64',
    messagingSenderId: '10860558957',
    projectId: 'billingapp-53d4c',
    storageBucket: 'billingapp-53d4c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCEldxlgAPeRvz-KpDRz_rYfyfpXO3CC4',
    appId: '1:10860558957:ios:5460f277580935a358dd64',
    messagingSenderId: '10860558957',
    projectId: 'billingapp-53d4c',
    storageBucket: 'billingapp-53d4c.firebasestorage.app',
    iosBundleId: 'com.example.billingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCEldxlgAPeRvz-KpDRz_rYfyfpXO3CC4',
    appId: '1:10860558957:ios:5460f277580935a358dd64',
    messagingSenderId: '10860558957',
    projectId: 'billingapp-53d4c',
    storageBucket: 'billingapp-53d4c.firebasestorage.app',
    iosBundleId: 'com.example.billingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpF1sOeS5lXXKhvnLIichapafkzfbAjX0',
    appId: '1:10860558957:web:0a80160d396ec40d58dd64',
    messagingSenderId: '10860558957',
    projectId: 'billingapp-53d4c',
    authDomain: 'billingapp-53d4c.firebaseapp.com',
    storageBucket: 'billingapp-53d4c.firebasestorage.app',
    measurementId: 'G-07WLYKRTEN',
  );
}
